### ISSUE TITLE
Fatal error: Call to undefined function Mdanter\Ecc\Curves\gmp_init() in /Applications/XAMPP/xamppfiles/htdocs/lpw1/huobi/src/Curves/NistCurve.php on line 165

### ISSUE THREAD

**Issue by lpwlpw** [del-xiong/huobi_rest_api#3]
Fatal error: Call to undefined function Mdanter\Ecc\Curves\gmp_init() in /Applications/XAMPP/xamppfiles/htdocs/lpw1/huobi/src/Curves/NistCurve.php on line 165

是不是版本的问题？

**Comment by del-xiong** [comment]
没安装gmp
